FROM python:3.12-slim

WORKDIR /app

COPY scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY scripts/import_data.py ./import_data.py

ENV PYTHONPATH=/app

CMD ["python", "import_data.py"]